---
- name: copy
  hosts: all

  tasks:

    - debug:
        msg: "Deploying {{ domain }}  {{ port }} "

    - name: Add new host
      template: 
            src: empresa
            dest: "/etc/nginx/sites-available/{{ domain }}.bbjetcloud.net"

    - name: ln
      file:
        src: '/etc/nginx/sites-available/{{ domain }}.bbjetcloud.net'
        dest: '/etc/nginx/sites-enabled/{{ domain }}.bbjetcloud.net'
        state: link

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes