---
- name: copy
  hosts: all

  tasks:

    - debug:
        msg: "Deleting {{ company }} "

    - name: Delete sa
      file:
        path: '/etc/nginx/sites-available/{{ company }}.bbjetcloud.net'
        state: absent

    - name: Delete se
      file:
        path: '/etc/nginx/sites-enabled/{{ company }}.bbjetcloud.net'
        state: absent

    - name: Delete sa-api
      file:
        path: '/etc/nginx/sites-available/api-{{ company }}.bbjetcloud.net'
        state: absent

    - name: Delete se-api
      file:
        path: '/etc/nginx/sites-enabled/api-{{company }}.bbjetcloud.net'
        state: absent

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes