---
- name: copy
  hosts: all
  vars:
    domain: empresa3
    port: 8083

  tasks:

    - debug:
        msg: "Deploying {{ domain }}  {{ port }} "

    - name: template test 1
      become: yes
      template: 
            src: empresa
            dest: "/etc/nginx/sites-available/{{ domain }}.bbjetcloud.net"

    - name: ln
      become: yes
      file:
        src: '/etc/nginx/sites-available/{{ domain }}.bbjetcloud.net'
        dest: '/etc/nginx/sites-enabled/{{ domain }}.bbjetcloud.net'
        state: link

    - name: Reload nginx
      become: yes
      service:
        name: nginx
        state: reloaded